version: '3.5'

networks:
  dockernet:
    driver: bridge

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql${MYSQL_VERSION}
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${SYNC_MYSQL_DATA_PATH}:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${MYSQL_HOST_PORT}:3306
    networks:
      - dockernet

  postgresql:
    image: postgres:${POSTGRESQL_VERSION}
    container_name: postgresql${POSTGRESQL_VERSION}
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - ${SYNC_POSTGRESQL_DATA_PATH}:/var/lib/postgresql/data:rw
    ports:
      - ${POSTGRESQL_HOST_PORT}:5432
    networks:
      - dockernet

  web:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - TIMEZONE=${TIMEZONE}
    image: htxuankhoa/php:${PHP_VERSION}
    container_name: php${PHP_VERSION}
    restart: always
    depends_on:
      - mysql
      - postgresql
    tty: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${APPLICATIONS}:/var/www
      - ${SYNC_APACHE2_ERROR_LOG_PATH}:/var/log/apache2/error.log
      - ./vhosts/sites:/etc/apache2/sites-available
      - ./php/php${PHP_INI_VERSION}.ini:/usr/local/etc/php/php.ini
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - dockernet
