version: '3'

services:
  db:
    image: mysql:${MYSQL_VERSION}
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ./sync/data/mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${MYSQL_HOST_PORT}:3306

  web:
    build:
      context: .
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
        - TIMEZONE=${TIMEZONE}
    image: htxuankhoa/web:latest
    container_name: web
    depends_on:
      - db
    links:
      - db
    restart: unless-stopped
    tty: true
    ports:
      - 80:80
    volumes:
      - ${APPLICATIONS}:/var/www
      - ./sync/logs/apache2_error.log:/var/log/apache2/error.log
      - ./vhosts/sites:/etc/apache2/sites-available
      - ./php/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
